<?php


namespace app\modules\backend\views;


class BackendModule extends \yii\base\Module
{
    public $defaultRoute = 'site';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}